services:
  backend:
    build:
      context: ./harbory-backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    restart: always
    # for production
    # healthcheck:
    #   test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    networks:
      - harbory-network

  frontend:
    build:
      context: ./harbory-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    restart: always
    depends_on: backend
      # backend:
        # condition: service_healthy
    networks:
      - harbory-network

networks:
  harbory-network:
    driver: bridge