services:
  backend:
    build:
      context: ./harbory-backend
      dockerfile: Dockerfile.dev
    expose:
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./harbory-backend:/app
    environment:
      - HARBORY_PASSWORD=${HARBORY_PASSWORD:-admin}
    privileged: true
    restart: always
    # for production
    # healthcheck:
    #   test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    networks:
      - harbory-network

  frontend:
    build:
      context: ./harbory-frontend
      dockerfile: Dockerfile.dev
    expose:
      - "5173"
    restart: always
    depends_on: 
      - backend
      # backend:
        # condition: service_healthy
    networks:
      - harbory-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    restart: always
    networks:
      - harbory-network

networks:
  harbory-network:
    driver: bridge
